name: Get Latest Release and Branch Tag

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  get_latest_tags:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取所有标签和完整历史

      - name: 获取最新发布版本标签
        run: |
          RESPONSE=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          RELEASE_TAG=$(echo "${RESPONSE}" | jq -r .tag_name)
          echo "最新发布的版本标签: ${RELEASE_TAG}"

      - name: 获取 myLazyNoSo 分支的最新标签
        run: |
          # 获取 myLazyNoSo 分支的所有标签，按时间倒序排列
          git fetch --tags  # 确保获取所有标签
          TAGS=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | grep -E '^v' | head -n 1)
          echo "myLazyNoSo 分支的最新标签: ${TAGS}"
