name: Get Latest Release Tag

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  get_latest_release:
    runs-on: ubuntu-latest

    steps:
      - name: 获取最新发布版本标签
        run: |
          RESPONSE=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          RELEASE_TAG=$(echo "${RESPONSE}" | jq -r .tag_name)
          echo "最新发布的版本标签: ${RELEASE_TAG}"
