name: Check and Rename APK

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的 runner

    steps:
      - name: 检出代码
        uses: actions/checkout@v2  # 检出项目代码

      - name: 检查 APK 文件并重命名
        run: |
          APK_DIR="app/build/outputs/apk/compatible/release"
          if [ -d "$APK_DIR" ] && ls "$APK_DIR"/*.apk 1> /dev/null 2>&1; then
            echo "找到 APK 文件，准备重命名最新的文件..."

            # 获取按时间倒序排列的最新 APK 文件
            LATEST_APK=$(ls -t "$APK_DIR"/*.apk | head -n 1)

            # 获取当前时间并格式化为 YYYYMMDD_HHMM
            TIMESTAMP=$(date +"%Y%m%d_%H%M")

            # 生成新的文件名
            NEW_NAME="XQE_Release_TAG_${TIMESTAMP}.apk"

            # 重命名文件
            mv "$LATEST_APK" "$APK_DIR/$NEW_NAME"
            echo "重命名成功: $NEW_NAME"
          else
            echo "没有找到 APK 文件或目录不存在"
          fi
