name: Log Dir

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的 runner

    steps:
      - name: 检出代码
        uses: actions/checkout@v2  # 检出项目代码

      - name: 打印当前目录文件
        run: |
          echo "当前目录的文件列表："
          ls -l  # 列出当前目录下的文件（详细列表）