name: Log Dir

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的 runner

    steps:
      - name: 检出代码
        uses: actions/checkout@v2  # 检出项目代码

      - name: 检查 app 文件夹是否存在并打印文件
        run: |
          if [ -d "app" ]; then  # 检查 app 文件夹是否存在
            echo "app 文件夹存在，列出其中的文件："
            ls -l app  # 列出 app 文件夹下的文件（详细列表）
          else
            echo "app 文件夹不存在"  # 如果 app 文件夹不存在，输出提示信息
          fi
