name: Log Info

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取所有标签和完整历史
        env:
          GIT_TERMINAL_PROMPT: 0  # 禁用 Git 终端提示，避免冗余输出
          GIT_SSH_COMMAND: "ssh -o LogLevel=QUIET"  # 禁用 SSH 日志输出
