name: 缓存Gradle

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查 Gradle 是否已安装并验证版本
        id: check_gradle
        run: |
          if gradle -v &>/dev/null; then
            INSTALLED_GRADLE_VERSION=$(gradle -v | grep "Gradle" | sed 's/.*Gradle \([0-9.]*\).*/\1/')
            echo "已安装 Gradle 版本: ${INSTALLED_GRADLE_VERSION}"
            if [ "$INSTALLED_GRADLE_VERSION" == "7.2" ]; then
              echo "Gradle 7.2 已安装"
              echo "gradle_installed=true" >> $GITHUB_ENV
            else
              echo "已安装的 Gradle 版本不是 7.2, 而是 $INSTALLED_GRADLE_VERSION"
              echo "gradle_installed=false" >> $GITHUB_ENV
            fi
          else
            echo "Gradle 未安装"
            echo "gradle_installed=false" >> $GITHUB_ENV
          fi

      - name: 缓存 Gradle 版本
        if: env.gradle_installed == 'false'
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-v7.2
          restore-keys: |
            gradle-${{ runner.os }}-v7.2

      - name: 下载并安装 Gradle 7.2
        if: env.gradle_installed == 'false'
        run: |
          GRADLE_VERSION=7.2
          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
          unzip gradle-${GRADLE_VERSION}-bin.zip -d /opt/gradle
          echo "/opt/gradle/gradle-${GRADLE_VERSION}/bin" >> $GITHUB_PATH  # 添加到 PATH

      - name: 验证 Gradle 安装
        run: gradle -v
