name: 使用 Gradle 7.2

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 设置 Gradle 缓存
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-v7.2
          restore-keys: |
            gradle-${{ runner.os }}-v7.2

      - name: 安装 Gradle 7.2
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          GRADLE_VERSION=7.2
          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
          unzip gradle-${GRADLE_VERSION}-bin.zip -d /opt/gradle
          echo "/opt/gradle/gradle-${GRADLE_VERSION}/bin" >> $GITHUB_PATH  # 添加到 PATH

      - name: 使用 Gradle Wrapper 构建项目
        run: ./gradlew build

      - name: 验证 Gradle 版本
        run: ./gradlew -v
