name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 检查 JDK 是否已安装
        id: check_jdk
        run: |
          if java -version &>/dev/null; then
            echo "JDK 已安装"
            echo "jdk_installed=true" >> $GITHUB_ENV
          else
            echo "JDK 未安装"
            echo "jdk_installed=false" >> $GITHUB_ENV
          fi

      - name: 缓存 JDK
        if: env.jdk_installed == 'false'
        uses: actions/cache@v3
        with:
          path: ~/.sdkman/candidates
          key: ${{ runner.os }}-jdk-11-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-jdk-11-

      - name: 安装 JDK 11
        if: env.jdk_installed == 'false'
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk

      - name: 验证 JDK 安装
        run: java -version

      - name: 检查 Gradle 是否已安装
        id: check_gradle
        run: |
          if gradle -v &>/dev/null; then
            echo "Gradle 已安装"
            echo "gradle_installed=true" >> $GITHUB_ENV
          else
            echo "Gradle 未安装"
            echo "gradle_installed=false" >> $GITHUB_ENV
          fi

      - name: 输出缓存路径和键
        run: |
          echo "当前缓存路径: ~/.gradle/caches"
          echo "当前缓存键: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*') }}"

      - name: 缓存 Gradle
        if: env.gradle_installed == 'false'
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 构建项目以下载依赖
        run: ./gradlew build --info

      - name: 安装 Gradle
        if: env.gradle_installed == 'false'
        run: |
          sudo apt update
          sudo apt install -y gradle

      - name: 验证 Gradle 安装
        run: gradle -v
