name: Update Badge

on:
  push:
    branches:
      - main_tk  # 修改为 main_tk 分支
  schedule:
    - cron: '0 * * * *' # 每小时运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 获取最新的 release 标签
      - name: Get latest release tag
        id: get_release
        run: |
          LATEST_TAG=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          
          echo "Latest release tag: $LATEST_TAG"
          echo "latest_release=$LATEST_TAG" >> $GITHUB_ENV  # 使用环境文件设置输出

      # 查看 README.md 中的当前版本
      - name: Check current version in README
        id: check_version
        run: |
          CURRENT_TAG=$(grep -oP 'tag=\K[^&]+' README.md | head -1)
          echo "Current version in README: $CURRENT_TAG"
          echo "current_version=$CURRENT_TAG" >> $GITHUB_ENV

      # 更新 README.md 中的版本标签
      - name: Update README if necessary
        id: update_readme
        run: |
          if [ "${{ env.latest_release }}" != "${{ env.current_version }}" ]; then
            sed -i "s|tag=${{ env.current_version }}|tag=${{ env.latest_release }}|g" README.md
            echo "Updated README.md with latest version"
            echo "needs_update=true" >> $GITHUB_ENV  # 标记需要更新
          else
            echo "README.md is already up to date."
            echo "needs_update=false" >> $GITHUB_ENV  # 标记不需要更新
          fi

      # 如果需要更新，则继续执行后续步骤
      - name: Check if update is needed
        run: |
          if [ "${{ env.needs_update }}" == "true" ]; then
            echo "Proceeding to commit and push changes."
          else
            echo "No update needed. Exiting workflow."
            exit 0  # 退出工作流
          fi

      # 查看 Git 状态
      - name: Check git status
        run: |
          git status

      # 设置 SSH 密钥并配置 SSH 代理
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 提交更改并推送
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git status  # 查看添加的文件
          git commit -m "Update README with latest version badge" || echo "No changes to commit"  # 添加错误处理
          git push git@github.com:${{ github.repository }}.git HEAD:main_tk
