name: Update Badge

on:
  push:
    branches:
      - main_tk  # 修改为 main_tk 分支
  schedule:
    - cron: '0 * * * *' # 每小时运行

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 获取最新的 release 标签
      - name: Get latest release tag
        id: get_release
        run: |
          LATEST_TAG=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "Latest release tag: $LATEST_TAG"
          echo "::set-output name=latest_release::$LATEST_TAG"

      # 更新 README.md 中的徽章链接
      - name: Update README
        run: |
          # 更新徽章 URL，兼容 v 前缀和没有 v 前缀的版本标签
          sed -i "s|v*[0-9]*\.[0-9]*\.[0-9]*\([.][0-9]*\)?[a-zA-Z0-9]*|${{ steps.get_release.outputs.latest_release }}|g" README.md

      # 提交更改
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update badge to latest release version"
          git push
