name: Update Badge

on:
  push:
    branches:
      - main_tk  # 修改为 main_tk 分支
  schedule:
    - cron: '0 * * * *' # 每小时运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 获取最新的 release 标签
      - name: Get latest release tag
        id: get_release
        run: |
          LATEST_TAG=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          
          echo "Latest release tag: $LATEST_TAG"
          echo "latest_release=$LATEST_TAG" >> $GITHUB_ENV  # 使用环境文件设置输出

      # 更新 README.md 中的 `${LATEST_VERSION}` 为最新的版本号
      - name: Update README
        run: |
          # 替换 README.md 中的 `${LATEST_VERSION}` 为实际的版本号
          sed -i "s|\${LATEST_VERSION}|${{ env.latest_release }}|g" README.md
          echo "Updated README.md"

      # 查看 Git 状态
      - name: Check git status
        run: |
          git status

      # 提交更改并推送
      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # 使用 GitHub Secrets 中的 PAT
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git status  # 查看添加的文件
          git commit -m "Update README with latest version badge" || echo "No changes to commit"  # 添加错误处理
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main_tk
